add security.01
YuraNR/online-book-store pull request #5
Opened 2023-11-15 20:02 UTC by YuraNR

2023-11-16 07:14 UTC, sonyasapsan approved these changes

2023-11-17 15:22 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/controller/BookController.java
> +    public List<BookDto> getAll(@PageableDefault(page = 0, size = 2, direction = Sort.Direction.ASC)
You ghouls add @PreAuthorize for endpoints

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) {
```

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/security/CustomUserDetailsService.java
> +
remove empty line

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.email()).isPresent()) {
It's better to create boolean existsByEmail method

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/UserServiceImpl.java
> +        user.setEmail(requestDto.email());
```suggestion
        user.setRole(Set.of(....
```

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
Check all sizes. They should be the same as in requests

2023-11-17 15:22 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/UserServiceImpl.java
> +@Component
```suggestion
@Service
```

2023-11-29 14:26 UTC, merged